### ISSUE TITLE
Add content from PowerPoints and brochure

### ISSUE THREAD

**Issue by mimiflynn** [morganstanley/cpx-training#22]
- [ ] Include video where possible
- [x] exercise descriptions
- [ ] Include training overview above list of exercise

**Comment by CraigGosnay** [comment]
taking a look at adding the exercise descriptions - @mimiflynn is L1-e3 correct? It seems to have the wrong code snippet

**Comment by mimiflynn** [comment]
That might be true, perhaps an update is needed to align it.

**Comment by CraigGosnay** [comment]
I can make the change i just wanted to confirm with you
